#!/bin/bash

# copy local mods to git directory
# done this way to lessen the possibility of sending private stuff to the repository

# assure we're on the right branch
branch=`cd /data/local/src/uw-idp-custom; git branch | grep '\*' | awk -e '{print $2}'`
[[ $branch == '4.1' ]] || {
   echo "uw-idp-custom must br set to 4.1 branch"
   exit 1
}

files="
fixperms
update-git
conf/access-control.xml
conf/admin/metrics.xml
conf/attribute-resolver-activators.j2
conf/attribute-resolver.xml.tmpl
conf/audit.xml
conf/authn/dynamic-mfa.base
conf/authn/general-authn.xml
conf/authn/mfa-authn-config.xml
conf/authn/uwduo-config.xml
conf/authn/wdmfa-config.xml
conf/core-filter.xml
conf/credentials.xml
conf/errors.xml
conf/global.xml
conf/idp.properties.tmpl
conf/intercept/google-check-intercept-config.xml
conf/intercept/slack-check-intercept-config.xml
conf/logback.xml
conf/metadata-providers.xml
conf/oidc.properties.tmpl
conf/relying-party.xml
conf/rs-filter.xml
conf/saml-nameid-exceptions.j2
conf/services.properties
conf/services.xml
conf/uw-auto-rps.xml.j2
flows/intercept/slack-check/slack-check-beans.xml
flows/intercept/slack-check/slack-check-flow.xml
flows/intercept/google-check/google-check-flow.xml
flows/intercept/google-check/google-check-beans.xml
flows/authn/crn-select/crn-select-beans.xml
flows/authn/crn-select/crn-select-flow.xml
flows/authn/duo-bypass/duo-bypass-flow.xml
flows/authn/duo-bypass/duo-bypass-beans.xml
flows/authn/uwduo/uwduo-flow.xml
flows/authn/uwduo/uwduo-beans.xml
flows/authn/disusered/disusered-flow.xml
flows/authn/needduo/needduo-flow.xml
views/login.vm
views/crnselect.vm
views/expiring-password.vm
views/error.vm
views/templates/add-html-body-content.vm
views/login-error.vm
views/no-slack.vm
views/logout-complete.vm
views/duo.vm
views/logout.vm
views/google-redirect.vm
views/needduo.vm
local-bin/README.python
local-bin/alert_conf.py
local-bin/alertlib.py
local-bin/cleanup_logs.sh
local-bin/cp_audit.sh
local-bin/filter_scan.py
local-bin/idp_master.py
local-bin/idp_master.sh
local-bin/idp_master_conf.py
local-bin/make_contacts.py
local-bin/md.functions
local-bin/netid_exception.py
local-bin/netid_exception.sh
local-bin/netid_exceptions_html.j2
local-bin/orphan_policy.py
local-bin/py-requirements.txt
local-bin/refresh_ic.sh
local-bin/refresh_uw.sh
local-bin/reload_attributeresolver
local-bin/reload_clientinfo
local-bin/reload_filter
local-bin/reload_logging
local-bin/reload_metadata
local-bin/reload_relyingparty
local-bin/reload_resolver
local-bin/restart_tomcat.sh
local-bin/sp-contacts.pl
local-bin/sp-contacts.sh
local-bin/spreg_conf_4.py
local-bin/spreg_update_4.py
local-bin/test_deps.sh
local-bin/verify_schema.sh
local-bin/vfy
messages/messages.properties
messages/authn-messages.properties
messages/error-messages.properties
"

dest="/data/local/src/uw-idp-custom"

num=0
for fp in $files
do
  path="${fp%/*}"
  [[ $path == $fp ]] && path='.'
  file="${fp##*/}"
  cmp -s $fp ${dest}/${path}/${file}
  (( $? == 0 )) && continue 
  [[ -d ${dest}/${path} ]] || mkdir -p ${dest}/${path}
  cp $fp ${dest}/${path}/${file}
  (( num = num + 1 ))
done

(( num==0 )) && echo "no changes" || echo "$num files updated"

